### ISSUE TITLE
Install.sh is downloading too much

### ISSUE THREAD

**Issue by Zerotistic** [WhereTheFuckIsMySerotonin/Pokemon_in_dah_terminal#1]
Please update install.sh so that it doesn't download all the pokemon, it's downloading waaay to much and take lot of place.
Thank you

**Comment by ForwardFeed** [comment]
It's in fact not downloading but expanding all the 651gifs to colored ascii art which takes useless amounts of Hard Drive space.
I'll add a full-install option and leave the default one just as a dependencies check.
